### ISSUE TITLE
hello, thanks for your work, could you tell me the version of onnxruntime? i have tested onnxruntime1.15, but didn't work!

### ISSUE THREAD

**Issue by GongmingHu** [tahaahiskali/yolov7-onnxruntime#1]

**Comment by tahaahiskali** [comment]
Hi @GongmingHu ,

**Environments**
_Ubuntu 18.04.6 LTS
CUDA 11.4
ONNXRuntime 1.12
Opencv 4.1_

I don't think the opencv version will change the result. But it must be CUDA and ONNXRuntime compatible. 

Please consider the table in the link. **https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html**

If it doesn't work, You can share the error on this thread.
