### ISSUE TITLE
About NMS

### ISSUE THREAD

**Issue by a5372935** [tahaahiskali/yolov7-onnxruntime#4]
I would like to ask you, are your code does not contain the nms algorithm?

**Comment by tahaahiskali** [comment]
YOLOv7 implements the nms algorithm within itself.

![image](https://github.com/tahaahiskali/yolov7-onnxruntime/assets/21156640/c00870c8-2931-4c89-b397-07a8d902b022)

**Comment by a5372935** [comment]
OK, and I'd also like to ask you about the onnx export command.

python export.py --weights /path/model.pt --end2end --simplify --topk-all 100 --iou-thres 0.3 --conf-thres 0.5 --img-size 1280 1280
Is there something wrong with this command?

**Comment by tahaahiskali** [comment]
https://colab.research.google.com/github/WongKinYiu/yolov7/blob/main/tools/YOLOv7onnx.ipynb

![image](https://github.com/tahaahiskali/yolov7-onnxruntime/assets/21156640/d940f2a4-8efb-4846-afa3-714b02a81678)

**Comment by tahaahiskali** [comment]
@a5372935  Could you please reply back when you solve your problem?

**Comment by a5372935** [comment]
I'm sorry I've been a little busy these past few days. Yes, I've already solved it.

But I'm using the following command

python export.py --weights ./yolo.pt --grid --end2end --topk-all 100 --iou-thres 0.3 --conf-thres 0.5 --img-size 1280 1280 --device cpu --max-wh 1280

NO simplify

**Comment by tahaahiskali** [comment]
Thanks for the feedback.
