### ISSUE TITLE
hello, I'am Chinese, I want to ask a question

### ISSUE THREAD

**Issue by 9479421** [tahaahiskali/yolov7-onnxruntime#5]
hello, I'am Chinese, how to get the yolov7-tiny.onnx, i try to use export.py to transfer yolov7.pt to **.onnx , but can't detect any objects.But It's successful to use your yolov7-tiny.onnx

**Comment by tahaahiskali** [comment]
#4 Can you follow the steps here?

**Comment by 9479421** [comment]
Thanks,I have resolved this problem. The result is that i ignore to set the yolov7 training param '--max-wh', so I failed to use the onnxruntime to detect picture yesterday. Others, Can we make a friend?  What's communcation software that your country using mostly？
